title: Stefanee Tillman # your name (or website title) here
logo: "/images/stefpic.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello World! Welcome to my portfolio where I demonstrate previous projects and my development in Statistics and Coding over time. 
  <br><br>
  I am an inquisitive individual that truly enjoys figuring out solutions to problems. 
  In my free time, I enjoys walks and trying different types of teas!
  <br><br>
  <a href="https://www.linkedin.com/in/stefanee-tillman-294a141b8">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
